### ISSUE TITLE
Exceptions under Redhat 6.6? 

### ISSUE THREAD

**Issue by jryberg** [HurricaneLabs/check_splunk#1]
Hi, Got exceptions and my python-fu is non existent. 

[root@some-host-name plugins]# /usr/lib64/nagios/plugins/check_splunk.py -H 127.0.0.1 -U admin -P supersecret --license-pool=auto_generated_pool_enterprise license
CRITICAL :: Exception follows
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/check_splunk.py", line 413, in <module>
    CheckSplunk().check().exit()
  File "/usr/lib64/nagios/plugins/check_splunk.py", line 155, in __init__
    epilog_lines.append("  {}{}".format(string.ljust(command, 30), f.description))
ValueError: zero length field name in format

[root@some-host-name plugins]# python --version
Python 2.6.6

May I have some help please?

**Comment by mcmasterathl** [comment]
@jryberg Please update to the newest revision and let me know if this fixes your problem.

Thanks.

**Comment by jryberg** [comment]
Hi,

Just tested. Got this error message instead

[root@some-host-name ~]# /usr/lib64/nagios/plugins/check_splunk.py -H 127.0.0.1 -U admin -P somepassword --license-pool=auto_generated_pool_enterprise license
CRITICAL :: Exception follows
Traceback (most recent call last):
  File "/usr/lib64/nagios/plugins/check_splunk.py", line 413, in <module>
    CheckSplunk().check().exit()
  File "/usr/lib64/nagios/plugins/check_splunk.py", line 215, in check
    return check(splunkd)
  File "/usr/lib64/nagios/plugins/check_splunk.py", line 250, in check_license
    (used, capacity, pct) = splunkd.get_license_pool_usage(self.options.license_pool)
  File "/usr/lib64/nagios/plugins/splunk.py", line 287, in get_license_pool_usage
    used = self.get_license_pool_used_bytes(pool)
  File "/usr/lib64/nagios/plugins/splunk.py", line 244, in get_license_pool_used_bytes
    return int(self.get_pool_info(pool)["used_bytes"])
  File "/usr/lib64/nagios/plugins/splunk.py", line 230, in get_pool_info
    root = self._get_url("/servicesNS/nobody/system/licenser/pools/{pool_name}", pool_name=pool)
  File "/usr/lib64/nagios/plugins/splunk.py", line 62, in _get_url
    self.check_for_error(self.cache["urls"][url])
  File "/usr/lib64/nagios/plugins/splunk.py", line 66, in check_for_error
    msg = root.find("./messages/msg[@type='ERROR']")
  File "/usr/lib64/python2.6/xml/etree/ElementTree.py", line 330, in find
    return ElementPath.find(self, path)
  File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 186, in find
    return _compile(path).find(element)
  File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 176, in _compile
    p = Path(path)
  File "/usr/lib64/python2.6/xml/etree/ElementPath.py", line 93, in __init__
    "expected path separator (%s)" % (op or tag)
SyntaxError: expected path separator ([)

Regards Johan

**Comment by mcmasterathl** [comment]
It appears XPath support wasn't added until Python 2.7. I will make a note that this plugin is not supported on Python 2.6. We'll welcome a patch to support 2.6 but since 2.6 is no longer supported, we won't be adding support for it.

http://stackoverflow.com/questions/15964232/xml-parsing-error-in-python-2-6
